#!/usr/bin/env bash
# deploy.sh — deploy mock_verifier + game_hub, initialize, register
# flight_scroll (game_id=1), then smoke-test with get_image_id.
#
# Usage:
#   scripts/deploy.sh                           # testnet, auto-generate + friendbot-fund
#   scripts/deploy.sh --network testnet
#   scripts/deploy.sh --network mainnet --identity my-prod-deployer
#   scripts/deploy.sh --identity my-existing-deployer --reuse
#
# Flags:
#   --network <testnet|mainnet>   default: testnet
#   --identity <name>             default: flight-deployer-<network>
#   --reuse                       allow reusing an existing identity (otherwise an
#                                 existing identity with the same name is a hard error)
#
# Side effects:
#   - builds contracts to wasm32v1-none/release
#   - builds the image-id printer
#   - writes apps/web/.env.local with VITE_GAME_HUB_CONTRACT_ID
#   - writes .deploy-keys.<network>.txt with the deployer keypair (chmod 600, gitignored)
#   - writes .deploy-state.<network> with contract ids (gitignored)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# ── Argument parsing ──────────────────────────────────────────────────────
NETWORK="testnet"
IDENTITY=""
REUSE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --network)
      NETWORK="$2"; shift 2 ;;
    --identity)
      IDENTITY="$2"; shift 2 ;;
    --reuse)
      REUSE=true; shift ;;
    -h|--help)
      sed -n '2,17p' "$0"; exit 0 ;;
    *)
      echo "[deploy] unknown flag: $1" >&2; exit 2 ;;
  esac
done

case "$NETWORK" in
  testnet|mainnet) ;;
  *) echo "[deploy] --network must be 'testnet' or 'mainnet', got '$NETWORK'" >&2; exit 1 ;;
esac

if [[ -z "$IDENTITY" ]]; then
  IDENTITY="flight-deployer-$NETWORK"
fi

echo "[deploy] network = $NETWORK · identity = $IDENTITY"

# ── Mainnet safety ────────────────────────────────────────────────────────
if [[ "$NETWORK" == "mainnet" ]]; then
  cat <<EOF >&2

  ⚠️  MAINNET DEPLOY
  This will consume real XLM and write to the production chain.
  Type 'I UNDERSTAND' to confirm:

EOF
  read -r CONFIRM
  if [[ "$CONFIRM" != "I UNDERSTAND" ]]; then
    echo "[deploy] aborted." >&2
    exit 1
  fi
fi

# ── Pre-flight ────────────────────────────────────────────────────────────
command -v stellar >/dev/null || { echo "[deploy] stellar CLI not found" >&2; exit 1; }

# ── Identity: resolve or generate ─────────────────────────────────────────
identity_exists() {
  stellar keys address "$1" --network "$NETWORK" >/dev/null 2>&1
}

if identity_exists "$IDENTITY"; then
  if [[ "$REUSE" != true ]]; then
    echo "[deploy] identity '$IDENTITY' already exists on $NETWORK." >&2
    echo "[deploy] pass --reuse to deploy from it, or --identity <other> to generate fresh." >&2
    exit 1
  fi
  echo "[deploy] reusing existing identity: $IDENTITY"
else
  echo "[deploy] generating identity: $IDENTITY"
  if [[ "$NETWORK" == "testnet" ]]; then
    stellar keys generate "$IDENTITY" --network "$NETWORK" --fund
    echo "[deploy] friendbot funded $IDENTITY"
  else
    stellar keys generate "$IDENTITY" --network "$NETWORK"
    DEPLOYER_ADDR_TMP="$(stellar keys address "$IDENTITY")"
    cat <<EOF
[deploy] mainnet identity created but UNFUNDED.
        Address: $DEPLOYER_ADDR_TMP
[deploy] Fund it with real XLM, then press Enter to continue (Ctrl-C to abort).
EOF
    read -r
  fi
fi

DEPLOYER_ADDR="$(stellar keys address "$IDENTITY")"
DEPLOYER_SECRET="$(stellar keys secret "$IDENTITY")"
echo "[deploy] deployer: $DEPLOYER_ADDR"

# ── Save keypair (gitignored, restrictive perms) ──────────────────────────
KEYFILE="$REPO_ROOT/.deploy-keys.$NETWORK.txt"
umask 077
cat > "$KEYFILE" <<EOF
# Auto-generated by scripts/deploy.sh — DO NOT COMMIT, DO NOT SHARE.
# Network:    $NETWORK
# Identity:   $IDENTITY
# Generated:  $(date -u +"%Y-%m-%dT%H:%M:%SZ")
DEPLOYER_PUBLIC=$DEPLOYER_ADDR
DEPLOYER_SECRET=$DEPLOYER_SECRET
EOF
chmod 600 "$KEYFILE"
echo "[deploy] keypair → $KEYFILE (chmod 600, gitignored)"

# ── Build contracts ───────────────────────────────────────────────────────
echo "[deploy] building contracts (wasm32v1-none/release) …"
(cd contracts && cargo build --target wasm32v1-none --release --quiet)

MOCK_WASM="contracts/target/wasm32v1-none/release/mock_verifier.wasm"
HUB_WASM="contracts/target/wasm32v1-none/release/game_hub.wasm"
[[ -f $MOCK_WASM ]] || { echo "[deploy] missing $MOCK_WASM" >&2; exit 1; }
[[ -f $HUB_WASM  ]] || { echo "[deploy] missing $HUB_WASM"  >&2; exit 1; }

# ── Image id ──────────────────────────────────────────────────────────────
echo "[deploy] building image-id printer …"
cargo build --release --bin image-id --quiet
IMAGE_ID="$(./target/release/image-id)"
echo "[deploy] FLIGHT_GUEST image_id: $IMAGE_ID"

# ── Deploy mock_verifier ──────────────────────────────────────────────────
echo "[deploy] deploying mock_verifier …"
MOCK_ID="$(stellar contract deploy --wasm "$MOCK_WASM" --source "$IDENTITY" --network "$NETWORK" 2>&1 | tail -1)"
echo "[deploy] mock_verifier: $MOCK_ID"

# ── Deploy game_hub ───────────────────────────────────────────────────────
echo "[deploy] deploying game_hub …"
HUB_ID="$(stellar contract deploy --wasm "$HUB_WASM" --source "$IDENTITY" --network "$NETWORK" 2>&1 | tail -1)"
echo "[deploy] game_hub: $HUB_ID"

# ── Initialize game_hub ───────────────────────────────────────────────────
echo "[deploy] game_hub::initialize(admin=$DEPLOYER_ADDR, verifier=$MOCK_ID) …"
stellar contract invoke --id "$HUB_ID" --source "$IDENTITY" --network "$NETWORK" \
  -- initialize --admin "$DEPLOYER_ADDR" --verifier "$MOCK_ID"

# ── Register flight_scroll as game_id=1 ───────────────────────────────────
echo "[deploy] game_hub::add_game(1, image_id) …"
stellar contract invoke --id "$HUB_ID" --source "$IDENTITY" --network "$NETWORK" \
  -- add_game --game_id 1 --image_id "$IMAGE_ID"

# ── Smoke test: get_image_id(1) ───────────────────────────────────────────
echo "[deploy] smoke: get_image_id(1) …"
GAME_OUT="$(stellar contract invoke --id "$HUB_ID" --source "$IDENTITY" --network "$NETWORK" \
  -- get_image_id --game_id 1)"
echo "[deploy] get_image_id(1) returned: $GAME_OUT"
if ! echo "$GAME_OUT" | grep -q "$IMAGE_ID"; then
  echo "[deploy] ⚠️  get_image_id did not echo the expected image_id — investigate." >&2
  exit 1
fi
echo "[deploy] ✅ smoke passed — game_id 1 registered with the right image_id."

# ── Persist for clients ───────────────────────────────────────────────────
cat > "$REPO_ROOT/.deploy-state.$NETWORK" <<EOF
NETWORK=$NETWORK
IDENTITY=$IDENTITY
DEPLOYER_ADDR=$DEPLOYER_ADDR
MOCK_VERIFIER_ID=$MOCK_ID
GAME_HUB_ID=$HUB_ID
FLIGHT_GUEST_IMAGE_ID=$IMAGE_ID
EOF
echo "[deploy] state → .deploy-state.$NETWORK (gitignored)"

# Per-network passphrase + RPC defaults
case "$NETWORK" in
  testnet)
    PASSPHRASE="Test SDF Network ; September 2015"
    RPC="https://soroban-testnet.stellar.org"
    ;;
  mainnet)
    PASSPHRASE="Public Global Stellar Network ; September 2015"
    RPC="https://mainnet.sorobanrpc.com"
    ;;
esac

cat > "$REPO_ROOT/apps/web/.env.local" <<EOF
# Auto-generated by scripts/deploy.sh — do not edit by hand.
VITE_GAME_HUB_CONTRACT_ID=$HUB_ID
VITE_STELLAR_NETWORK_PASSPHRASE=$PASSPHRASE
VITE_STELLAR_RPC_URL=$RPC
EOF
echo "[deploy] web env → apps/web/.env.local (gitignored)"

echo
echo "[deploy] ✅ done — network: $NETWORK"
echo "  game_hub:       $HUB_ID"
echo "  mock_verifier:  $MOCK_ID"
echo "  image_id (1):   $IMAGE_ID"
echo
echo "Next:"
echo "  pnpm --filter @flight/web build && pnpm --filter @flight/web preview"
echo "  → Connect Wallet, play the game locally."
echo "  → After a great run, dump transcript (T key), then:"
echo "    ./scripts/prove.sh transcript.bin --player <YOUR_G_STRKEY>"
echo "  → Upload proof_artifacts.json in the wallet panel to submit_score."
