#!/usr/bin/env bash
# deploy.sh — deploy mock_verifier + game_hub to Stellar testnet,
# initialize, and register flight_scroll (game_id=1).
#
# Prereqs:
#   1. `stellar` CLI 25.x installed.
#   2. A funded testnet identity. Quickstart:
#        stellar keys generate flight-deployer --network testnet --fund
#      That uses friendbot to give the new keypair test XLM.
#
# Usage:
#   scripts/deploy.sh [identity-name]
#     identity-name defaults to: flight-deployer
#
# Side effects:
#   - builds contracts to wasm32v1-none/release
#   - builds the image-id printer
#   - writes apps/web/.env.local with VITE_GAME_HUB_CONTRACT_ID
#   - prints contract ids to stdout (also captured in .deploy-state)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

IDENTITY="${1:-flight-deployer}"
NETWORK=testnet

echo "[deploy] identity = $IDENTITY · network = $NETWORK"

# ── Pre-flight ────────────────────────────────────────────────────────────
command -v stellar >/dev/null || { echo "[deploy] stellar CLI not found"; exit 1; }

if ! stellar keys address "$IDENTITY" --network "$NETWORK" >/dev/null 2>&1; then
  echo "[deploy] identity '$IDENTITY' not found."
  echo "[deploy] create + fund one with:"
  echo "         stellar keys generate $IDENTITY --network $NETWORK --fund"
  exit 1
fi

DEPLOYER_ADDR="$(stellar keys address "$IDENTITY")"
echo "[deploy] deployer address: $DEPLOYER_ADDR"

# ── Build ────────────────────────────────────────────────────────────────
echo "[deploy] building contracts (wasm32v1-none/release) …"
(cd contracts && cargo build --target wasm32v1-none --release --quiet)

MOCK_WASM="contracts/target/wasm32v1-none/release/mock_verifier.wasm"
HUB_WASM="contracts/target/wasm32v1-none/release/game_hub.wasm"
[[ -f $MOCK_WASM ]] || { echo "[deploy] missing $MOCK_WASM"; exit 1; }
[[ -f $HUB_WASM  ]] || { echo "[deploy] missing $HUB_WASM"; exit 1; }

echo "[deploy] building image-id printer …"
cargo build --release --bin image-id --quiet
IMAGE_ID="$(./target/release/image-id)"
echo "[deploy] flight_guest image_id: $IMAGE_ID"

# ── Deploy mock_verifier ─────────────────────────────────────────────────
echo "[deploy] deploying mock_verifier …"
MOCK_ID="$(stellar contract deploy \
  --wasm "$MOCK_WASM" \
  --source "$IDENTITY" \
  --network "$NETWORK" 2>&1 | tail -1)"
echo "[deploy] mock_verifier contract id: $MOCK_ID"

# ── Deploy game_hub ──────────────────────────────────────────────────────
echo "[deploy] deploying game_hub …"
HUB_ID="$(stellar contract deploy \
  --wasm "$HUB_WASM" \
  --source "$IDENTITY" \
  --network "$NETWORK" 2>&1 | tail -1)"
echo "[deploy] game_hub contract id: $HUB_ID"

# ── Initialize game_hub ──────────────────────────────────────────────────
echo "[deploy] game_hub::initialize(admin=$DEPLOYER_ADDR, verifier=$MOCK_ID) …"
stellar contract invoke \
  --id "$HUB_ID" \
  --source "$IDENTITY" \
  --network "$NETWORK" \
  -- initialize \
  --admin "$DEPLOYER_ADDR" \
  --verifier "$MOCK_ID"

# ── Register flight_scroll as game_id=1 ──────────────────────────────────
echo "[deploy] game_hub::add_game(1, image_id=$IMAGE_ID, name=\"flight_scroll\") …"
stellar contract invoke \
  --id "$HUB_ID" \
  --source "$IDENTITY" \
  --network "$NETWORK" \
  -- add_game \
  --game_id 1 \
  --image_id "$IMAGE_ID" \
  --name "flight_scroll"

# ── Persist for clients ──────────────────────────────────────────────────
cat > "$REPO_ROOT/.deploy-state" <<EOF
DEPLOYER_ADDR=$DEPLOYER_ADDR
MOCK_VERIFIER_ID=$MOCK_ID
GAME_HUB_ID=$HUB_ID
FLIGHT_GUEST_IMAGE_ID=$IMAGE_ID
EOF

cat > "$REPO_ROOT/apps/web/.env.local" <<EOF
# Auto-generated by scripts/deploy.sh — do not edit by hand.
VITE_GAME_HUB_CONTRACT_ID=$HUB_ID
VITE_STELLAR_NETWORK_PASSPHRASE=Test SDF Network ; September 2015
VITE_STELLAR_RPC_URL=https://soroban-testnet.stellar.org
EOF

echo
echo "[deploy] done."
echo "  game_hub:       $HUB_ID"
echo "  mock_verifier:  $MOCK_ID"
echo "  image_id (1):   $IMAGE_ID"
echo
echo "Next:"
echo "  pnpm --filter @flight/web build && pnpm --filter @flight/web preview"
echo "  → open the URL, Connect Wallet, play the game locally."
echo "  → after a great run, dump the transcript (T key), then:"
echo "    ./scripts/prove.sh transcript.bin --player <YOUR_G_STRKEY>"
echo "  → upload proof_artifacts.json in the wallet panel to submit_score."
